/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComponentePresentacion;

import ComponenteEntidad.Categoria;
import ComponenteNegocio.CategoriaCN;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.omg.CORBA.OBJECT_NOT_EXIST;

/**
 *
 * @author Rita
 */
public class DialogCategoria extends javax.swing.JDialog {

    /**
     * Creates new form DialogCategoria
     */
    boolean reg;
    DefaultTableModel modelo = new DefaultTableModel();
    String nombreColumnas[] = {"idCategoria", "nombre", "Descripcion"};

    public DialogCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setSize(800,635);
        textos(false);

        modelo.setColumnIdentifiers(nombreColumnas);
        buscar();
    }

    public void buscar() {
        try {
            List<Categoria> categorias = CategoriaCN.getInstancia().lista();
            Object datos[][] = new Object[categorias.size()][3];
            for (int i = 0; i < categorias.size(); i++) {
                Categoria categoria = categorias.get(i);
                datos[i][0] = categoria.getIdCategoria();
                datos[i][1] = categoria.getNombre();
                datos[i][2] = categoria.getDescripcion();
            }
            modelo.setDataVector(datos, nombreColumnas);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnRegirtrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btnEliminacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CATEGORIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        txtDes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 310, 90));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("idCategoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txtIdCategoria.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, -1));

        btnRegirtrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRegirtrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1436818314_button_ok.png"))); // NOI18N
        btnRegirtrar.setText("REGISTRAR");
        btnRegirtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegirtrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegirtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 130, 40));

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 670, 270));

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reservas.png"))); // NOI18N
        jButton3.setText("NUEVO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 130, 40));

        btnEliminacion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnEliminacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1449578379_document_delete.png"))); // NOI18N
        btnEliminacion.setText("ELIMINAR");
        btnEliminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 130, 40));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1436817581_Log Out.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Neko_Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void limpiarTextos() {
        txtIdCategoria.setText("");
        txtDes.setText("");
        txtNombre.setText("");
        txtDes.setText("");
    }

    void textos(boolean verdad) {
        txtIdCategoria.setEditable(verdad);
        txtDes.setEditable(verdad);
        txtNombre.setEditable(verdad);

    }
    private void btnRegirtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegirtrarActionPerformed
       if(txtIdCategoria.getText().compareTo("")!=0){ 
        String codigo = txtIdCategoria.getText();
        String des = txtDes.getText();
        String nombre = txtNombre.getText();
        Categoria categoria = new Categoria(codigo, des, nombre);
        try {
            if (reg) {
                CategoriaCN.getInstancia().crearCategoria(categoria);
                JOptionPane.showMessageDialog(rootPane, "Se registro sus datos.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "no se registro los Datos");
            }
            buscar();
            limpiarTextos();
        

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
       } else
        JOptionPane.showMessageDialog(null,"faltan llenar datos");


    }//GEN-LAST:event_btnRegirtrarActionPerformed

    private void btnEliminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminacionActionPerformed

        String idCategoria = JOptionPane.showInputDialog("Id de la categoria: ");
        try {
            Categoria cat = CategoriaCN.getInstancia().BuscarCategoria(idCategoria);
            if (cat != null) {
                txtIdCategoria.setText(cat.getIdCategoria());
                txtDes.setText(cat.getDescripcion());
                txtNombre.setText(cat.getNombre());
                int respuesta = JOptionPane.showConfirmDialog(rootPane, "Deseas eliminar?", "Eliminar", JOptionPane.OK_CANCEL_OPTION);
                if (respuesta == JOptionPane.OK_OPTION) {
                    CategoriaCN.getInstancia().eliminarCategoria(cat);
                }
                limpiarTextos();
                buscar();
                textos(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Categoria no existe.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminacionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reg = true;
        textos(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogCategoria dialog = new DialogCategoria(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminacion;
    private javax.swing.JButton btnRegirtrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
